{% set name = "osm-flex" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/osm-flex-{{ version }}.tar.gz
  sha256: 5a45e28bc8280eb4dcaf7d776efa3792bc46583ab8ade2d70609dad3894111fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - pip
  run:
    - python >={{ python_min }}
    - cartopy
    - geopandas
    - gdal
    - numpy
    - shapely >=2.0
    - pandas
    - tqdm

test:
  imports:
    - osm_flex
  source_files:
    - tests
  commands:
    - pip check
    # NOTE: Extraction does not work due to unexpanded environment variable $SRC_DIR
    #       in OSM_FILE variable
    # NOTE: Testing does not work on Windows due to backslashes in paths
    - pytest --ignore tests/test_extract.py tests/  # [not win]
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  summary: Python package for flexible data extraction from OpenStreetMap
  description: |
    This packages allows to

    1. download OSM data dumps
    2. [optional] clip to desired shape
    3. extract specific features to geodataframes
    4. [optional] simplify results based on geospatial operations
  license: GPL-3.0-or-later
  license_file: LICENSE
  home: https://github.com/osm-flex/osm-flex

extra:
  recipe-maintainers:
    - peanutfun
